### ISSUE TITLE
[feature] Supporting inline components?

### ISSUE THREAD

**Issue by felipesere** [nathancahill/dainte#81]
Hi!

Thanks for creating `dainte`! It looks pretty cool.
The one part I missed in the testing story of Svelte was the ability to mount 2-3 components
that are interconnected via stores/context.

For example, if I had a component that represents a checkbox `[ ]Guest View` and i had multiple other components that gray things out or show promo codes or do anything "when previewing as a guest", I would like to demonstrate in a test that "hitting this checkbox, will make these promo-codes show up" or similar. 

```
import { mount } from 'dainte'
import { tick } from 'svelte'
import { GuestView } from './Guest.svelte'
import { MyFancyWidget } from './MyFancyWidget.svelte'

it('hides prices and previews the promo codes for guests', async () => {
  const {document} = mount('<div><GuestView /><MyFancyWidget /></div>');

  await switchToGuestPreview(document);

  const promoCode = await findPromoCode(document);

  expect(promoCode).toEqual('ABC123');
}
``` 

The example above is super made-up.

Do you think such a thing will be possible in the future with Dainte?

**Comment by nathancahill** [comment]
I think you'd have to to create a small fixture component around the `Guest` and `MyFancyWidget` component and test that. This is what we're using for testing `Sveltik`, very simple example: https://github.com/nathancahill/sveltik/blob/master/tests/fixtures/as-component.svelte

I believe Dainte will always be focused on compiling from a source file and not from a string, the dependency resolution between the test imports and the string are very tricky to do robustly.

**Comment by nathancahill** [comment]
__`PreviewFixture.svelte`__
```jsx
import { GuestView } from './Guest.svelte'
import { MyFancyWidget } from './MyFancyWidget.svelte'

<div><GuestView /><MyFancyWidget /></div>
```

__`test.js`__
```js

it('hides prices and previews the promo codes for guests', async () => {
  const {document} = mount('./PreviewFixture.svelte');
  ...
}

```

**Comment by nathancahill** [comment]
Going to close this for now. If I think of a better way of injecting the test imports into an inline component I'll reopen. But for now we'll leave the resolution to Rollup.
